(defun issorted (L)
  (if (nth 0 L)
    (if (nth 1 L)
      (if (< (first L) (nth 1 L))
        (issorted (cdr L))
        ()
      )
      T
    )
    T
  )
)

(defun numbers(N)
  (if (>= 0 N)
    ()
    (if (= 1 N)
      (cons 1 ())
      (append (numbers (- N 1)) (cons N ()))
    )
  )
)

(defun palindrome (L)
  (if (null L)
    T
    (if (eq (first L) (car (last L)))
      (palindrome (reverse (cdr (reverse (cdr L)))))
      ()
    )
  )
)

(defun replace1 (Atom1 Atom2 L)
  (write 'L)
  (if (null L)
    ()
    (if (eq Atom1 (first L))
      (cons Atom2 (replace1 Atom1 Atom2 (cdr L)))
      (cons (first L) (replace1 Atom1 Atom2 (cdr L)))
    )
  )

)
